<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>3WA Restaurant</title>
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/font-awesome-4.3.0.min.css">

    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/3wa-resto.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-button.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-form.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-table.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla">
    <script src="https://kit.fontawesome.com/9b99b32647.js" crossorigin="anonymous"></script>
    
    <!-- Librairie jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
</head>
<body>

<!-- En-tête commune -->
<header>
    <h1>
        <a href="<?= $requestUrl ?>">
            <img src="<?= $wwwUrl ?>/images/logo.gif" height="63" width="57" alt="3WA Restaurant">Restaurant - Made In America !
        </a>
    </h1>
</header>

<!-- Interface utilisateur -->
<nav class="user-interface">
    <ul class="link-list">
        <!-- Code HTML/PHP à écrire -->
        <?php if($userSession->isAuthentificated()==true ):?>
    
                
            <a href="<?=$requestUrl?>/booking" class="button button-primary"> Réserver</a>
            <a href="<?=$requestUrl?>/order" class="button button-primary"> Commander</a></button>
            <a href="<?=$requestUrl?>/user/logout" class="button button-primary layout-right"> Déconnexion </a>
        
        <?php if($userSession->getAdmin()==1):?>

            <a href="<?=$requestUrl?>/admin" class="button button-primary" > Admin</a>
            <a href="<?=$requestUrl?>/admin/meal" class="button button-primary"> Meal</a></button>
            <a href="<?=$requestUrl?>/admin/user" class="button button-primary"> Admin User</a></button>
        
            <strong> Bonjour <em class="primary"> <?=$userSession->getFirstName().' '.$userSession->getLastName() ?></em> </strong>
            <a href="<?=$requestUrl?>/user/logout" class="button button-primary layout-right" > Déconnexion </a></button>
        
        <?php endif ;else:?>
            <a href="<?=$requestUrl?>/user" class="button button-primary" > Créer un compte</a>
            <a href="<?=$requestUrl?>/user/login" class="button button-primary layout-right"> Se connecter </a>
        <?php endif;?>
    </ul>
</nav>

<main>
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template'] ?>
</main>

<!-- Pied de page commun -->
<footer>
    <ul class="link-list">
        <li><img src="<?= $wwwUrl ?>/images/payment/visa.png" alt="Visa"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/mastercard.png" alt="MasterCard"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/paypal.png" alt="PayPal"></li>
    </ul>
    <small>Réalisé avec <i class="fa fa-heart"></i>&nbsp; par les élèves de la 3W Academy</small>
</footer>

<!-- Code principal JavaScript de l'application -->
<script src="<?= $wwwUrl ?>/js/main.js"></script>
<script src="<?= $wwwUrl ?>/js/classes/FormValidator.class.js"></script>

</body>
</html>