   <h2 data-order-step="success">Commande Payée</h2>
    <strong>Merci d'avoir commandé au 3WA Restaurant!</strong>
    <p> Votre commande a bien été enregistrée, elle vous sera livrée dans les plus brefs délais </p>

    <img src="<?= $wwwUrl ?>/images/success.gif">
    <br><br><br>
    <a href="<?=$requestUrl?>" class="button button-primary">Accueil</a>

<!-- Classes JavaScript du formulaire de commande -->
<script src="<?= $wwwUrl ?>/js/classes/OrderForm.class.js"></script>
<script src="<?= $wwwUrl ?>/js/classes/Basket.class.js"></script>